@endpoint = http://localhost:8000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhNmM2ZWYyYy04ZjIwLTQxMTMtODU1NS02NzQyMzEyZDU0NTkiLCJpYXQiOjE3MTI3MzgxNTEsImV4cCI6MTcxMjgyNDU1MX0.V8a7YrWfA5sp0Qd8yYZLVM-WERa4iIZoCPUeR_mdN1s

### 작품 저장
POST {{endpoint}}/pieces
Cookie: accessToken={{accessToken}}
Content-Type: application/json

{
  "title": "임시 작품",
  "material": "abc",
  "year": null
}

### 작품 조회
GET {{endpoint}}/pieces/85075472-3696-43f1-8db4-410887d24339

### 내 작품 리스트 조회
GET {{endpoint}}/pieces/my
Cookie: accessToken={{accessToken}}

### 작품 리스트 조회
GET {{endpoint}}/pieces
