@endpoint = http://localhost:8000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbHVjcTNjZHQwMDAxbjl1OGNuOTRtaGp3IiwiaWF0IjoxNzExOTYzNjE1LCJleHAiOjE3MTIwNTAwMTV9.dsrHe3boojp4P7rFQ702c6Gyi29k0AxvgYClGiZ2AL0

### 임시 작품 저장
POST {{endpoint}}/temp-pieces
Cookie: accessToken={{accessToken}}
Content-Type: application/json

{
  "title": "임시 작품",
  "exhibited": true
}