@endpoint = http://localhost:8000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhNmM2ZWYyYy04ZjIwLTQxMTMtODU1NS02NzQyMzEyZDU0NTkiLCJpYXQiOjE3MTIxNDA3MDUsImV4cCI6MTcxMjIyNzEwNX0.5zzdVxkqXvU9L7zP7YpcNgfQLEprCgTDqgcdj153xpA

### 임시 작품 저장
POST {{endpoint}}/temp-pieces
Cookie: accessToken={{accessToken}}
Content-Type: application/json

{
  "title": "임시 작품",
  "exhibited": true,
  "authorComment": "abc
  abc
  abc"
}

### 임시 작품 조회
GET {{endpoint}}/temp-pieces/e3ad8541-ea6b-499f-afa2-bfc0351a6254
Cookie: accessToken={{accessToken}}

### 임시 작품 리스트 조회
GET {{endpoint}}/temp-pieces
Cookie: accessToken={{accessToken}}

### 임시 작품 수정
PUT {{endpoint}}/temp-pieces/e3ad8541-ea6b-499f-afa2-bfc0351a6254
Cookie: accessToken={{accessToken}}
Content-Type: multipart/form-data; boundary=data

--data
Content-Disposition: form-data; name="title"

abc
--data
Content-Disposition: form-data; name="exhibited"

false
--data
Content-Disposition: form-data; name="file"; filename="image.png"
Content-Type: image/png

< ./images/chicken.png
--data--

### 임시 작품 삭제
DELETE {{endpoint}}/temp-pieces/e3ad8541-ea6b-499f-afa2-bfc0351a6254
Cookie: accessToken={{accessToken}}