@endpoint = http://localhost:8000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbHVjcTNjZHQwMDAxbjl1OGNuOTRtaGp3IiwiaWF0IjoxNzExOTc2MjIzLCJleHAiOjE3MTIwNjI2MjN9.Z4eFkhO6kqWoMZLG2V0JmhO2PQXzJNqAAL2IESs_qaQ

### 내 정보 조회
GET {{endpoint}}/my-info
Cookie: accessToken={{accessToken}}

### 내 정보 수정
PUT {{endpoint}}/my-info
Cookie: accessToken={{accessToken}}
Content-Type: application/json

{
  "email": "temp@naver.com",
  "name": "tempName"
}